import { StyleSheet } from 'react-native';

const AppStyle = StyleSheet.create({
  title: {
    marginLeft: 12,
    marginTop: 12,
    fontSize: 16,
  },
  textNote: {
    marginLeft: 12,
    marginVertical: 4,
    color: 'grey',
  },
  textNoteCheckbox: {
    marginLeft: 45,
    marginTop: -10,
    marginBottom: 5,
    color: 'grey',
  },
  nonEditableInput: {
    height: 50,
    marginVertical: 5,
    borderWidth: 1,
    borderRadius: 6,
    borderColor: 'darkgrey',
    padding: 5,
    fontSize: 16,
  },
  input: {
    height: 50,
    marginHorizontal: 10,
    marginVertical: 5,
    borderWidth: 1.5,
    borderRadius: 6,
    borderColor: 'lightgrey',
    padding: 5,
    fontSize: 16,
  },
  multilineInput: {
    marginHorizontal: 10,
    marginVertical: 5,
    borderColor: 'lightgrey',
    borderWidth: 1.5,
    borderRadius: 6,
    padding: 5,
    fontSize: 16,
    minHeight: 50,
    paddingTop: 10,
    paddingBottom: 15,
    lineHeight: 23,
  },
  nonEditableMultilineInput: {
    backgroundColor: '#dfdfdf',
    marginHorizontal: 10,
    marginVertical: 5,
    borderColor: 'darkgrey',
    borderWidth: 1,
    borderRadius: 6,
    padding: 5,
    fontSize: 16,
    minHeight: 50,
    paddingTop: 10,
    paddingBottom: 15,
    lineHeight: 23,
  },
  radioButtonContainer: {
    height: 30,
    marginTop: 10,
    marginBottom: 5,
    marginRight: 10,
    justifyContent: 'flex-start',
    paddingLeft: 10,
    paddingRight: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  radioButtonIcon: {
    backgroundColor: 'white',
    borderWidth: 1.5,
    borderColor: 'gray',
    height: 30,
    width: 30,
    borderRadius: 30 / 2,
    marginRight: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioButtonDisabledIcon: {
    backgroundColor: 'lightgrey',
    borderWidth: 1.5,
    borderColor: 'gray',
    height: 30,
    width: 30,
    borderRadius: 30 / 2,
    marginRight: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioButtonInnerIcon: {
    height: 25,
    width: 25,
    borderRadius: 12.5,
    borderWidth: 4,
    borderColor: 'white',
  },
  radioButtonText: {
    fontSize: 16,
  },
  selectDropdown: {
    marginVertical: 5,
    width: '100%',
    borderRadius: 6,
  },
  selectDropdownText: {
    fontSize: 16,
  },
  checkBoxContainer: {
    borderWidth: 0,
    marginLeft: 0,
  },
  checkBoxText: {
    fontSize: 16,
    fontWeight: 'normal',
  },
});

export default AppStyle;
